services:
  postgres:
    image: postgres:14-alpine
    container_name: simple-bank-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
      - DEBUG=true
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bank-network
  redis:
    image: redis:7-alpine
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://bankroot:secret@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - bank-network
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]
volumes:
  data-volume:
networks:
  bank-network:
    driver: bridge
    name: bank-network
